services:
  postgres:
    image: 'postgres:latest'
    container_name: ova-db
    environment:
      - POSTGRES_DB=ovasdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    networks:
      - red-backend-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ovasdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    image: angiecobo/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - red-backend-app

  ova-service:
    image: angiecobo/ova-service:latest
    container_name: ova-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ovasdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - JPA_DDL=create-drop
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - red-backend-app
    profiles:
      - app

networks:
  red-backend-app:
    driver: bridge
